import base64
import hashlib
import hmac
import json
import os
import secrets
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional


ROOT_DIR = Path(__file__).resolve().parents[1]
CONFIG_DIR = ROOT_DIR / 'config'
CREDENTIALS_FILE = CONFIG_DIR / 'credentials.json'
GOOGLE_GMAIL_SCOPES = [
    'openid',
    'email',
    'profile',
    'https://www.googleapis.com/auth/gmail.readonly',
]
GOOGLE_USERINFO_URL = 'https://www.googleapis.com/oauth2/v2/userinfo'
GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token'
SESSION_COOKIE_NAME = 'email_shield_session'
OAUTH_STATE_COOKIE_NAME = 'email_shield_oauth_state'

SCHEMA_BLUEPRINTS: Dict[str, str] = {
    'users': '''
create table if not exists public.users (
  user_uuid uuid primary key,
  display_email text not null unique,
  encrypted_refresh_token text not null,
  active_monitoring boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
''',
    'scan_history': '''
create table if not exists public.scan_history (
  id bigint generated by default as identity primary key,
  user_uuid uuid not null references public.users(user_uuid) on delete cascade,
  message_id text not null,
  thread_id text,
  source text not null,
  sender text not null,
  subject text not null,
  risk_score integer not null default 0,
  timestamp timestamptz not null default now(),
  triggered_flags jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_uuid, message_id)
);
''',
}


def _read_json_file(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        with path.open('r', encoding='utf-8') as file_handle:
            data = json.load(file_handle)
    except (OSError, ValueError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def _app_secret(env_name: str, fallback: str) -> str:
    value = os.getenv(env_name)
    if value:
        return value
    return fallback


def _derive_key(secret: str) -> bytes:
    return hashlib.sha256(secret.encode('utf-8')).digest()


def _xor_bytes(payload: bytes, key_stream: bytes) -> bytes:
    return bytes(byte ^ key_stream[index] for index, byte in enumerate(payload))


def _keystream(key: bytes, nonce: bytes, length: int) -> bytes:
    chunks: List[bytes] = []
    counter = 0
    while sum(len(chunk) for chunk in chunks) < length:
        chunks.append(hmac.new(key, nonce + counter.to_bytes(4, 'big'), hashlib.sha256).digest())
        counter += 1
    return b''.join(chunks)[:length]


def encrypt_refresh_token(refresh_token: str, secret: Optional[str] = None) -> str:
    token_secret = _derive_key(secret or _app_secret('APP_TOKEN_ENCRYPTION_KEY', 'email-shield-dev-token-secret'))
    nonce = secrets.token_bytes(16)
    payload = refresh_token.encode('utf-8')
    cipher_text = _xor_bytes(payload, _keystream(token_secret, nonce, len(payload)))
    digest = hmac.new(token_secret, nonce + cipher_text, hashlib.sha256).digest()
    return base64.urlsafe_b64encode(nonce + cipher_text + digest).decode('ascii')


def decrypt_refresh_token(cipher_text: str, secret: Optional[str] = None) -> str:
    token_secret = _derive_key(secret or _app_secret('APP_TOKEN_ENCRYPTION_KEY', 'email-shield-dev-token-secret'))
    try:
        raw_payload = base64.urlsafe_b64decode(cipher_text.encode('ascii'))
    except (ValueError, UnicodeDecodeError) as exc:
        raise ValueError('Invalid encrypted refresh token payload') from exc

    if len(raw_payload) < 16 + 32:
        raise ValueError('Encrypted refresh token payload is too short')

    nonce = raw_payload[:16]
    stored_cipher_text = raw_payload[16:-32]
    stored_digest = raw_payload[-32:]
    expected_digest = hmac.new(token_secret, nonce + stored_cipher_text, hashlib.sha256).digest()
    if not hmac.compare_digest(stored_digest, expected_digest):
        raise ValueError('Encrypted refresh token integrity check failed')

    plain_text = _xor_bytes(stored_cipher_text, _keystream(token_secret, nonce, len(stored_cipher_text)))
    return plain_text.decode('utf-8')


def sign_payload(payload: Dict[str, Any], secret: Optional[str] = None) -> str:
    session_secret = _derive_key(secret or _app_secret('APP_SESSION_SECRET', 'email-shield-dev-session-secret'))
    payload_json = json.dumps(payload, separators=(',', ':'), sort_keys=True).encode('utf-8')
    signature = hmac.new(session_secret, payload_json, hashlib.sha256).digest()
    encoded_payload = base64.urlsafe_b64encode(payload_json).decode('ascii').rstrip('=')
    encoded_signature = base64.urlsafe_b64encode(signature).decode('ascii').rstrip('=')
    return f'{encoded_payload}.{encoded_signature}'


def create_csrf_state() -> str:
    return sign_payload({'nonce': secrets.token_urlsafe(24), 'issued_at': int(time.time())}, secret='oauth-state')


def validate_csrf_state(token: str, max_age_seconds: int = 600) -> Dict[str, Any]:
    payload = verify_signed_payload(token, secret='oauth-state')
    issued_at = int(payload.get('issued_at', 0) or 0)
    if max_age_seconds and int(time.time()) - issued_at > max_age_seconds:
        raise ValueError('OAuth state has expired')
    return payload


def verify_signed_payload(token: str, secret: Optional[str] = None) -> Dict[str, Any]:
    session_secret = _derive_key(secret or _app_secret('APP_SESSION_SECRET', 'email-shield-dev-session-secret'))
    try:
        encoded_payload, encoded_signature = token.split('.', 1)
        payload_bytes = base64.urlsafe_b64decode(encoded_payload + '=' * (-len(encoded_payload) % 4))
        signature_bytes = base64.urlsafe_b64decode(encoded_signature + '=' * (-len(encoded_signature) % 4))
    except (ValueError, UnicodeDecodeError, base64.binascii.Error) as exc:
        raise ValueError('Invalid signed payload format') from exc

    expected_signature = hmac.new(session_secret, payload_bytes, hashlib.sha256).digest()
    if not hmac.compare_digest(signature_bytes, expected_signature):
        raise ValueError('Signed payload verification failed')

    data = json.loads(payload_bytes.decode('utf-8'))
    if not isinstance(data, dict):
        raise ValueError('Signed payload must decode to a JSON object')
    return data


def generate_state_token() -> str:
    return secrets.token_urlsafe(32)


def _credentials_config() -> Dict[str, Any]:
    config = _read_json_file(CREDENTIALS_FILE)
    web_config = config.get('web') if isinstance(config.get('web'), dict) else {}
    installed_config = config.get('installed') if isinstance(config.get('installed'), dict) else {}
    merged = {**installed_config, **web_config}
    return {
        'client_id': os.getenv('GOOGLE_CLIENT_ID') or merged.get('client_id', ''),
        'client_secret': os.getenv('GOOGLE_CLIENT_SECRET') or merged.get('client_secret', ''),
        'auth_uri': merged.get('auth_uri', 'https://accounts.google.com/o/oauth2/v2/auth'),
        'token_uri': os.getenv('GOOGLE_TOKEN_URI') or merged.get('token_uri', GOOGLE_TOKEN_URL),
        'redirect_uris': merged.get('redirect_uris', []),
        'project_id': merged.get('project_id', ''),
    }


def get_google_client_config() -> Dict[str, Any]:
    config = _credentials_config()
    if not config['client_id'] or not config['client_secret']:
        raise RuntimeError('Google OAuth client configuration is missing in config/credentials.json or environment variables.')
    return config


def resolve_google_redirect_uri(request_base_url: Optional[str] = None) -> str:
    configured = os.getenv('GOOGLE_OAUTH_REDIRECT_URI', '').strip()
    if configured:
        return configured
    config = _credentials_config()
    redirect_uris = config.get('redirect_uris') or []
    if isinstance(redirect_uris, list) and redirect_uris:
        first_uri = redirect_uris[0]
        if isinstance(first_uri, str) and first_uri.strip():
            return first_uri.strip()
    if request_base_url:
        return request_base_url.rstrip('/') + '/auth/callback'
    return 'http://127.0.0.1:8000/auth/callback'


def build_google_authorization_url(redirect_uri: str, state: str, scopes: Optional[List[str]] = None) -> str:
    config = get_google_client_config()
    authorization_params = {
        'response_type': 'code',
        'client_id': config['client_id'],
        'redirect_uri': redirect_uri,
        'scope': ' '.join(scopes or GOOGLE_GMAIL_SCOPES),
        'access_type': 'offline',
        'prompt': 'consent',
        'include_granted_scopes': 'true',
        'state': state,
    }
    return config['auth_uri'] + '?' + urllib.parse.urlencode(authorization_params)


def exchange_google_authorization_code(code: str, redirect_uri: str) -> Dict[str, Any]:
    config = get_google_client_config()
    payload = urllib.parse.urlencode(
        {
            'code': code,
            'client_id': config['client_id'],
            'client_secret': config['client_secret'],
            'redirect_uri': redirect_uri,
            'grant_type': 'authorization_code',
        }
    ).encode('utf-8')
    request = urllib.request.Request(
        config.get('token_uri') or GOOGLE_TOKEN_URL,
        data=payload,
        headers={'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'application/json'},
        method='POST',
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            response_body = response.read().decode('utf-8')
    except urllib.error.HTTPError as exc:
        error_body = exc.read().decode('utf-8', errors='replace') if exc.fp else str(exc)
        raise RuntimeError(f'Google token exchange failed: {error_body}') from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f'Google token exchange failed: {exc}') from exc

    data = json.loads(response_body)
    if not isinstance(data, dict):
        raise RuntimeError('Google token exchange returned an unexpected payload')
    return data


def fetch_google_userinfo(access_token: str) -> Dict[str, Any]:
    request = urllib.request.Request(
        GOOGLE_USERINFO_URL,
        headers={'Authorization': f'Bearer {access_token}', 'Accept': 'application/json'},
        method='GET',
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            response_body = response.read().decode('utf-8')
    except urllib.error.HTTPError as exc:
        error_body = exc.read().decode('utf-8', errors='replace') if exc.fp else str(exc)
        raise RuntimeError(f'Google userinfo request failed: {error_body}') from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f'Google userinfo request failed: {exc}') from exc

    data = json.loads(response_body)
    if not isinstance(data, dict):
        raise RuntimeError('Google userinfo returned an unexpected payload')
    return data


def google_user_uuid(google_subject: str, display_email: str) -> str:
    seed = google_subject or display_email.lower().strip()
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f'google:{seed}'))


def build_scan_history_record(
    user_uuid: str,
    scan_result: Dict[str, Any],
    source: str = 'gmail',
    timestamp: Optional[str] = None,
) -> Dict[str, Any]:
    result = scan_result if isinstance(scan_result, dict) else {}
    flags = result.get('flags', []) if isinstance(result.get('flags', []), list) else []
    return {
        'user_uuid': user_uuid,
        'source': source,
        'sender': result.get('sender') or 'Unknown Sender',
        'subject': result.get('subject') or 'No Subject',
        'risk_score': int(result.get('risk_score') or 0),
        'timestamp': timestamp or result.get('received_at') or time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
        'triggered_flags': flags,
        'message_id': result.get('message_id') or '',
        'thread_id': result.get('thread_id'),
        'status': result.get('status', 'clean'),
    }


def _request_json(base_url: str, service_role_key: str, method: str, path: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
    normalized_base_url = base_url.rstrip('/')
    request_url = normalized_base_url + path
    if params:
        request_url += '?' + urllib.parse.urlencode(params, doseq=True)

    request_body = None
    headers = {
        'apikey': service_role_key,
        'Authorization': f'Bearer {service_role_key}',
        'Accept': 'application/json',
        'Content-Type': 'application/json',
    }
    if body is not None:
        request_body = json.dumps(body).encode('utf-8')

    request = urllib.request.Request(request_url, data=request_body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            response_text = response.read().decode('utf-8')
            if not response_text.strip():
                return None
            return json.loads(response_text)
    except urllib.error.HTTPError as exc:
        error_body = exc.read().decode('utf-8', errors='replace') if exc.fp else str(exc)
        raise RuntimeError(f'Supabase request failed: {error_body}') from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f'Supabase request failed: {exc}') from exc


class SupabaseStore:
    def __init__(self, base_url: str, service_role_key: str) -> None:
        self.base_url = base_url.rstrip('/')
        self.service_role_key = service_role_key

    @classmethod
    def from_env(cls) -> 'SupabaseStore':
        base_url = os.getenv('SUPABASE_URL', '').strip()
        service_role_key = os.getenv('SUPABASE_SERVICE_ROLE_KEY', '').strip()
        if not base_url or not service_role_key:
            raise RuntimeError('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set')
        return cls(base_url, service_role_key)

    def _request(self, method: str, path: str, params: Optional[Dict[str, Any]] = None, body: Optional[Any] = None) -> Any:
        return _request_json(self.base_url, self.service_role_key, method, path, params=params, body=body)

    def get_user(self, user_uuid: str) -> Optional[Dict[str, Any]]:
        results = self._request(
            'GET',
            '/rest/v1/users',
            params={'select': '*', 'user_uuid': f'eq.{user_uuid}', 'limit': 1},
        )
        if isinstance(results, list) and results:
            first_result = results[0]
            return first_result if isinstance(first_result, dict) else None
        return None

    def list_active_users(self) -> List[Dict[str, Any]]:
        results = self._request(
            'GET',
            '/rest/v1/users',
            params={
                'select': 'user_uuid,display_email,encrypted_refresh_token,active_monitoring',
                'active_monitoring': 'eq.true',
                'order': 'updated_at.asc',
            },
        )
        return [item for item in results if isinstance(item, dict)] if isinstance(results, list) else []

    def upsert_user(self, user_row: Dict[str, Any]) -> Dict[str, Any]:
        results = self._request(
            'POST',
            '/rest/v1/users',
            params={'on_conflict': 'user_uuid'},
            body=[user_row],
        )
        if isinstance(results, list) and results:
            first_result = results[0]
            if isinstance(first_result, dict):
                return first_result
        return user_row

    def list_user_scans(self, user_uuid: str, limit: int = 25) -> List[Dict[str, Any]]:
        results = self._request(
            'GET',
            '/rest/v1/scan_history',
            params={
                'select': '*',
                'user_uuid': f'eq.{user_uuid}',
                'order': 'timestamp.desc',
                'limit': str(limit),
            },
        )
        return [item for item in results if isinstance(item, dict)] if isinstance(results, list) else []

    def upsert_scan_history(self, scan_row: Dict[str, Any]) -> Dict[str, Any]:
        results = self._request(
            'POST',
            '/rest/v1/scan_history',
            params={'on_conflict': 'user_uuid,message_id'},
            body=[scan_row],
        )
        if isinstance(results, list) and results:
            first_result = results[0]
            if isinstance(first_result, dict):
                return first_result
        return scan_row
